services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: yahs_user
      MYSQL_PASSWORD: yahs_password
      MYSQL_DATABASE: yahs
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - internal_network
    ports:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - '6379'
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mysql-data:
  redis-data:

networks:
  internal_network:
    driver: bridge