spring:
  security:
    oauth2:
      client:
        registration:
          hanzec:
            client-id: ${YAHS_OAUTH_CLIENT_ID:client_id}
            client-secret: ${YAHS_OAUTH_CLIENT_SECRET:client_secret}
        provider:
          hanzec:
            authorization-uri: https://login.hanzec.com/application/o/authorize/
            token-uri: https://login.hanzec.com/application/o/token/
            user-info-uri: https://login.hanzec.com/application/o/userinfo/
            jwk-set-uri: https://login.hanzec.com/application/o/yahs/jwks/