spring:
  config:
    import:
      - "classpath:/config/compose.yaml"
      - "classpath:/config/database.yaml"
      - "classpath:/config/springdoc.yaml"
  profiles:
    active: dev
  application:
    name: 'yahs'