package com.hanzec.yats.model.constants;

public enum IApiPermission {
    ACCESS_ADMIN_CONSOLE,
    READ_TAILNET_POLICY_FILE,
    WRITE_TAILNET_POLICY_FILE,
    READ_NETWORK_CONFIGURATION,
    WRITE_NETWORK_CONFIGURATION,
    READ_FEATURE_CONFIGURATION,
    WRITE_FEATURE_CONFIGURATION,
    CONFIGURE_USER_GROUP_PROVISIONING,
    READ_MACHINE_INFORMATION,
    WRITE_MACHINE_INFORMATION,
    READ_USER_INFORMATION,
    WRITE_USER_INFORMATION,
    GENERATE_API_TOKEN,
    SHARE_NODE,
    ACCEPT_SHARE_NODES,
    USE_TAG_IF_NOT_OWNER,
    READ_CONFIGURATION_AUDIT_LOG,
    USE_SSH_CONSOLE_IF_ALLOWED,
    WRITE_WEBHOOKS,
    UPDATE_TAILNET_NAME,
    READ_PAYMENT_PLAN,
    WRITE_PAYMENT_PLAN,
    WRITE_PAYMENT_HISTORY
}
