package com.hanzec.yats.model.constants;

public enum ISubscriptableEvent {
    NODE_CREATED,
    NODE_NEEDS_APPROVAL,
    NODE_APPROVED,
    NODE_KEY_EXPIRING_ONE_DAY,
    NODE_KEY_EXPIRED,
    NODE_DELETED,
    POLICY_UPDATED,
    USER_CREATED,
    USER_NEEDS_APPROVAL,
    USER_SUSPENDED,
    USER_DELETED,
    USER_APPROVED,
    USER_ROLE_UPDATED,
    SUBNET_IP_FORWARDING_NOT_ENABLED,
    EXIT_NODE_IP_FORWARDING_NOT_ENABLED,
}
